import React from "react";
import DownloadExampleData from "../../../shared/DownloadExampleData";

export default function StudentDataExample() {
  const title = "Mẫu file dữ liệu Sinh viên";
  const fileName = "v1.2/sinh-vien-example.xlsx";
  const head = [
    "Mã số sinh viên*",
    "Họ tên*",
    "Ngày sinh*",
    "Giới tính",
    "Email*",
    "Khóa",
    "Lớp",
    "Khoa/Viện*",
    "CTĐT*",
    "Số Tín chỉ*",
    "Số năm tối thiểu*",
    "Số năm tối đa*",
  ];
  const body = [
    [
      20195753,
      "Đỗ Hòa An",
      "09/24/2001",
      "Nam",
      "an.dh295753@sis.hust.edu.vn",
      64,
      "Kỹ thuật máy tính 01-K64",
      "Viện Công nghệ Thông tin và Truyền thông",
      "Kỹ thuật máy tính - K64",
      156,
      4,
      8,
    ],
    [
      20195754,
      "Hoàng Đình Lương An",
      "12/26/2001",
      "Nam",
      "an.hdl195755@sis.hust.edu.vn",
      64,
      "Kỹ thuật máy tính 02-K64",
      "Viện Công nghệ Thông tin và Truyền thông",
      "Kỹ thuật máy tính - K64",
      156,
      4,
      8,
    ],
    [
      20195755,
      "Bùi Hải Anh",
      "12/26/2001",
      "Nam",
      "anh.bh955755@sis.hust.edu.vn",
      64,
      "Kỹ thuật máy tính 01-K64",
      "Viện Công nghệ Thông tin và Truyền thông",
      "Kỹ thuật máy tính - K64",
      156,
      4,
      8,
    ],
    [
      20195756,
      "Bùi Quang Anh",
      "11/14/2001",
      "Nam",
      "anh.bq5756@sis.hust.edu.vn",
      64,
      "Kỹ thuật máy tính 02-K64",
      "Viện Công nghệ Thông tin và Truyền thông",
      "Kỹ thuật máy tính - K64",
      156,
      4,
      8,
    ],
    [
      20196277,
      "Đào Hoàng Anh",
      "07/17/2001",
      "Nam",
      "anh.dh196277@sis.hust.edu.vn",
      64,
      "Kỹ thuật máy tính 01-K64",
      "Viện Công nghệ Thông tin và Truyền thông",
      "Kỹ thuật máy tính - K64",
      156,
      4,
      8,
    ],
    [
      20196278,
      "Đào Lương Duy Anh",
      "07/20/2001",
      "Nam",
      "anh.dld296278@sis.hust.edu.vn",
      64,
      "Kỹ thuật máy tính 01-K64",
      "Viện Công nghệ Thông tin và Truyền thông",
      "Kỹ thuật máy tính - K64",
      156,
      4,
      8,
    ],
    // [
    //   20195757,
    //   "Hoàng Việt Anh",
    //   "05/27/2001",
    //   "Nam",
    //   "anh.hv5757@sis.hust.edu.vn",
    //   64,
    //   "Kỹ thuật máy tính 02-K64",
    //   "Viện Công nghệ Thông tin và Truyền thông",
    //   "Kỹ thuật máy tính - K64",
    //   156,
    //   4,
    //   8,
    // ],
    // [
    //   20195758,
    //   "Lê Đoàn Hải Anh",
    //   "Nam",
    //   "anh.ldh195758@sis.hust.edu.vn",
    //   64,
    //   "Kỹ thuật máy tính 01-K64",
    //   "Viện Công nghệ Thông tin và Truyền thông",
    //   "Kỹ thuật máy tính - K64",
    //   156,
    //   4,
    //   8,
    // ],
    // [
    //   20195759,
    //   "Nguyễn Duy Tùng Anh",
    //   "12/22/2001",
    //   "Nam",
    //   "anh.ndt195759@sis.hust.edu.vn",
    //   64,
    //   "Kỹ thuật máy tính 02-K64",
    //   "Viện Công nghệ Thông tin và Truyền thông",
    //   "Kỹ thuật máy tính - K64",
    //   156,
    //   4,
    //   8,
    // ],
  ];
  return <DownloadExampleData {...{ title, fileName, head, body }} minWidth={"2000px"}></DownloadExampleData>;
}
